# Generated by Django 3.0.4 on 2020-03-25 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registeration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(max_length=256, null=True)),
                ('Last_name', models.CharField(max_length=256, null=True)),
                ('Gender', models.CharField(choices=[('MALE', 'The Gender is Male'), ('FEMALE', 'The Gender is female'), ('OTHERS', 'The Gender is others'), ('NONE', 'The Gender NONE')], default='NONE', max_length=128)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Phone', models.IntegerField(max_length=13, null=True, unique=True)),
                ('City', models.CharField(max_length=128)),
            ],
        ),
    ]
