# Generated by Django 3.0.4 on 2020-04-01 18:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('application_1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer_configuration',
            name='lan_ip',
        ),
        migrations.AddField(
            model_name='customer_configuration',
            name='black_list_urls',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='customer_configuration',
            name='categories_to_block',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='customer_configuration',
            name='countries_to_block',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='customer_configuration',
            name='lan_IP',
            field=models.GenericIPAddressField(null=True),
        ),
        migrations.AddField(
            model_name='customer_configuration',
            name='last_modified',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='customer_configuration',
            name='subscription_type',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='customer_configuration',
            name='white_list_urls',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='customer_configuration',
            name='created_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='customer_configuration',
            name='current_status',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='customer_configuration',
            name='customer_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customer_configuration',
            name='plan_end_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='customer_configuration',
            name='plan_start_date',
            field=models.DateTimeField(null=True),
        ),
    ]
