# Generated by Django 3.0.4 on 2020-04-01 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application_1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer_configuration',
            name='user',
        ),
        migrations.AddField(
            model_name='customer_configuration',
            name='customer_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='application_1.UserProfileModel'),
        ),
    ]
