# Generated by Django 3.0.4 on 2020-03-25 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application_1', '0003_auto_20200325_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='registeration',
            name='Password',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='registeration',
            name='Username',
            field=models.CharField(max_length=128, null=True, unique=True),
        ),
    ]
