# Generated by Django 3.0.4 on 2020-04-01 19:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('application_1', '0003_auto_20200401_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_configuration',
            name='customer_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
