# Generated by Django 3.0.4 on 2020-03-31 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application_1', '0005_auto_20200331_1151'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofilemodel',
            options={},
        ),
        migrations.CreateModel(
            name='customer_configuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lan_ip', models.GenericIPAddressField()),
                ('organisation_name', models.CharField(max_length=128, null=True)),
                ('plan_start_date', models.DateTimeField()),
                ('plan_end_date', models.DateTimeField()),
                ('current_status', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField()),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='application_1.UserProfileModel')),
            ],
        ),
    ]
