# Generated by Django 3.0.4 on 2020-03-31 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application_1', '0006_auto_20200331_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_configuration',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application_1.UserProfileModel'),
        ),
    ]
